### ISSUE TITLE
testing SIMD instruction sets are available (3502)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1729]
# **Issue &numero;3502 opened by *[illume](https://github.com/illume)* at 2022-10-16 11:39:40**

We have conditional compilation, and conditionally choose different instruction sets at runtime. So do SDL and other dependencies.

So how to test if our releases work on older CPUs without instruction sets (SSE4.2, AVX2, AVX-512, etc)?

https://github.com/pygame/pygame/pull/3498#issuecomment-1279949951

Probably running the tests an extra time with no AVX2 available under the intel sde64 emulator on each of (mac, linux, windows) is enough. We do also support some SSE4.2 functions, and support for that isn't as wide as SSE2... so maybe another test for no-SSE4.2 is useful.

sde64: https://www.intel.com/content/www/us/en/developer/articles/tool/software-development-emulator.html

```bash

$ sde64 -snb -- python -m pygame.tests

```

ARM neon is another one, because some still supported raspberry pi boards don't do neon. Haven't researched how to do this, but I guess qemu at least could be useful here.<hr>

# Comments

**Comment by MyreMylar** [comment]
I think we have sufficient testing for the SIMD platforms we support on CI. SSE2/neon gets a good workout on Arm and AVX2 on most everything else. We are limited somewhat by what is available on CI, but we are not flush enough with funds & time to dig out old hardware and software combos to test manually if the latest version of pygame-ce still works. 

I also don't think we should make too much effort to make it work on ancient hardware, because that is what older versions of pygame/pygame-ce are for. Pygame-ce should focus most of our (limited) energy on working on the majority of hardware/software combo platforms that are used today.  Yes, fix any obvious bugs identified, but I'm not going to be too bothered if we introduce a bug on windows 3.1 capable machines and don't notice for a while.
