### ISSUE TITLE
pygame.transform.blur

### ISSUE THREAD

**Issue by ScriptLineStudios** [pygame-community/pygame-ce#1908]
```python
pygame.transform.blur(surf: pygame.Surface) -> pygame.Surface
```

**Comment by yoyoberenguer** [comment]
Hello, not sure if you have completed the task, but I wanted to share some of my experience regarding this process 
A good technique to simplify the blurring is actually to reduce the size of the image prior processing and re-scaling the image after processing. Pygame scaling routines are well optimized and can be used for this task.

That way, instead of blurring an image size 1280x1024 you could blur 800x600 instead.
Regarding the Gaussian blurring effect another good technique is to decomposed the kernel into two passes (vertical and horizontal) to simplify the amount of calculation needed. 

What about the border of the image? In the blurring process the image border usually goes darker since the lack of values  included in the Kernel computation.

Is your algorithm working for both types 24 and 32-bit surface? 
The process is slightly different, since the surface data has to be decomposed into RGB and alpha with a slight performance decrease. 

Here is an example of Blur performances using Cython 
```Python
BCK = pygame.transform.smoothscale(BCK, (1280, 1024))
T = 200
import timeit
t = timeit.timeit(
    "blur(BCK)",
    "from __main__ import blur, BCK",
    number=T)
print("cython : ", t/T)
```
---
```python
cython :  0.024679664 --> for  image size 1280x1024
cython :  0.009065428  --> for image size 800x600
```
It would be beneficial if the method could returns a tuple (Surface, Array) as sometime you want to continue processing the array with other techniques or needs to apply other special effects before converting the array back into a surface

It is also good to have the choice between: 
1 - The surface is blurred and the change is applied to a copy
2 - The surface is blurred INPLACE (must faster)
