### ISSUE TITLE
PyGame seems to be running through X11 on top if wayland

### ISSUE THREAD

**Issue by JaskRendix** [pygame-community/pygame-ce#2058]
Hello there,
thanks for the new release 2.2.0.
I was doing some testing on Tuxemon, everything works, but when running the game, I get this warning:
```
/home/robespierre/Tuxemon/tuxemon/prepare.py:140: Warning: PyGame seems to be running through X11 on top if wayland, instead of wayland directly
  SCREEN = pg.display.set_mode(SCREEN_SIZE, flags)
```
Is it my "old" PC the issue? I'm not really into X11 or wayland.

**Comment by oddbookworm** [comment]
Can you provide a bit more info? Go ahead and provide the output of `pygame.print_debug_info()`

**Comment by JaskRendix** [comment]
@oddbookworm you're right, as requested:
```
Platform:		Linux-5.15.0-67-generic-x86_64-with-glibc2.35
System:			Linux
System Version:		#74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023
Processor:		x86_64
Architecture:		Bits: 64bit	Linkage: ELF
Driver:			x11

Python:			CPython
pygame version:		2.2.0
python version:		3.10.6

SDL versions:		Linked: 2.0.22	Compiled: 2.0.22
SDL Mixer versions:	Linked: 2.6.2	Compiled: 2.6.2
SDL Font versions:	Linked: 2.20.1	Compiled: 2.20.1
SDL Image versions:	Linked: 2.0.5	Compiled: 2.0.5
Freetype versions:	Linked: 2.12.1	Compiled: 2.12.1
```

**Comment by robertpfeiffer** [comment]
This error can be ignored if everything works. 

But if you are having trouble with windowing or window decorations or something like that, you could run `export SDL_VIDEODRIVER=wayland` to set an environment variable, or `SDL_VIDEODRIVER=wayland python3 my_game.py` and then re-run the program to have PyGame talk to your wayland compositor (e.g. sway, hikari, gnome-shell, kwin) directly, and not through an X11 compatibility layer. At some point in the future, wayland support in SDL will be stable enough so SDL will switch to prefer speaking wayland to wayland over speaking X11 to wayland, and this will disappear.

So why is this warning there? Well, wayland doesn't do everything X11 does, for reasons of security and API simplicity. So certain things that used to work on X11 won't work on wayland. But if you query whether you are running on sway or gnome-shell/kwin in wayland mode, it will tell you that it's running on X11, because of the xwayland compatibility layer. You'll wonder why things don't work. This is just the worst of both worlds from a bug tracking perspective. So we added this little check that warns you: Actually there is a wayland session running, but we are speaking X11 to the compositor.

**Comment by ankith26** [comment]
As robertpfeiffer correctly pointed above, this is a warning and not an error, as an end user you can safely ignore this if you app works as you expect.

However, if you are interested and have time to spare I would appreciate your efforts it if you could help in testing a WIP PR (#1997) that I have that makes it possible for pygame to use wayland directly. You can navigate under the CI runs of that PR, download the wheel artifacts, install the wheel for your python version and architecture, and test your app in the way mentioned above (by setting `SDL_VIDEODRIVER=wayland`). 

It can happen that something that works breaks, or something broken starts working with this change. I'd like to know your observations

**Comment by JaskRendix** [comment]
Thanks to everyone. I'm going to close the issue.
@ankith26 I'll look into, eventually I'll report directly in the PR #1997
