### ISSUE TITLE
Incorrect rendering of Unicode glyphs with fonts utilizing dynamic resizing. (191)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#206]
# **Issue &numero;191 opened by *[illume](https://github.com/illume)* at 2014-01-21 19:02:48**

Originally reported by: **Anonymous**

----------------------------------------

I've built pygame from the mercurial repo, but I've deleted the build files, so I don't have a sha for the commit. I compiled it last week though.
I'm using python 3.3 and compiled pygame for python3 as well.  Using Slackware 14.1 on x86_64. I've supplied images of how pygame renders the glyphs using this code: https://gist.github.com/ironhouzi/8545318

The unicode I've used བསྐྱོངས
The codepoints:
U+0F56
U+0F66
U+0F90
U+0FB1
U+0F7C
U+0F44
U+0F66

Same but in ord values:
3926
3942
3984
4017
3964
3908
3942

----------------------------------------
- Bitbucket: https://bitbucket.org/pygame/pygame/issue/191
<hr>

# Comments

**Comment by zoldalma999** [comment]
While the original code is now not available, the wayback machine did luckly [save](https://web.archive.org/web/20200624145102/https://bitbucket.org/pygame/pygame/issues/191/) the original issue. After downloading the "Noto Serif Tibetian" font from google fonts, I could get the same result as seen in both the original image, the browser, and my code editor with this script:
```python
import pygame
pygame.init()

screen = pygame.display.set_mode((200, 200))
screen.fill((0, 0, 0))

font = pygame.font.Font("NotoSerifTibetan-Regular.ttf", 20)
font.set_script("Tibt")

screen.blit(font.render("བསྐྱོངས", True, (255, 255, 255)), (20, 20))
pygame.display.flip()

for i in range(5):
    pygame.event.get()
    pygame.time.wait(1000)

pygame.quit()
``` Not sure what the "utilizing dynamic resizing" part means here, but since this was opened in 2014, I don't think I can reach the original author, so I'll be closing this.
