### ISSUE TITLE
pygame.display.get_rect() and pygame.display.get_size()

### ISSUE THREAD

**Issue by JiffyRob** [pygame-community/pygame-ce#2245]
**Description**
As title says.  The two functions would be similar to the surface API, but be called directly on the module.  It gets annoying to have to call `pygame.display.get_surface().get_rect()`.  Also there might be some optimization here if we don't need the surface, just the size.

**Comment by Starbuck5** [comment]
The upcoming Window API has a `size` attribute. But that's a separate thing, it's also settable.

Since the upcoming API already has something like this, and because I don't think calling `pygame.display.get_surface().get_rect()` is a very common operation in people's code, I am not in favor of adding the additional code to support those functions.

**Comment by zoldalma999** [comment]
I agree with Starbuck here, I don't think we want too much more things to the display module which specifically operates on the "main window" (created with set_mode). I'll wait a bit for opinions, but will close this in a week or so if there is no support for it.
