### ISSUE TITLE
`sys.getsizeof()` doesn't get the real size of a surface.

### ISSUE THREAD

**Issue by yunline** [pygame-community/pygame-ce#2296]
```py
import sys

import pygame
sf = pygame.Surface((640,480))
print(sys.getsizeof(sf)) # 64

import numpy
array = numpy.zeros((640,480,3), numpy.uint8)
print(sys.getsizeof(array)) # 921744
```

Currently `sys.getsizeof(sf)` returns the size of the `pgSurfaceObject` structure. The size of pixels is not included.
However, in numpy, the `sys.getsizeof` returns the real size of array (`921744 = 640 * 480 * 3 + 144`)

So I think we should add the size of the pixels to the result of `getsizeof()`

**Comment by itzpr3d4t0r** [comment]
Agree on this one.

**Comment by ankith26** [comment]
This may actually be tricky to get right. Given the dimensions of the surface, I don't think it's possible to easily know the exact size it needs in memory. And of the top of my head I don't know any SDL API for this either

**Comment by itzpr3d4t0r** [comment]
I mean we know the size, we know the bpp, just two multiplications no?

**Comment by ankith26** [comment]
Well, that would be part of the work, but it wouldn't be the "real size" because `SDL_Surface` has many other internal fields that take memory, that could be harder to measure. 
I'm not saying it's impossible to get right, but would it be worth the effort? I mean, I don't think `getsizeof` returning wrong things can break anything (apart from maybe some stats)

**Comment by Matiiss** [comment]
Well, returning structure size + bytes taken up by the pixels + pitch would at least bring the estimate far closer to reality since I wouldn't think `SDL_Surface`'s other fields take up significant amounts of memory, of course this would less affect larger surfaces and the smaller ones would suffer more from this inaccuracy, but it would be at least something. Of course the argument could be made that it's better to keep it as is rather than introducing a half baked solution.

**Comment by itzpr3d4t0r** [comment]
Agree, I've actually made a more precise version that's very close to the limit of what we have control over since we can't have access to some internal sdl structs:
```C
static PyObject *
pg_surface_get_bytesize(PyObject *self, PyObject *_null)
{
    SDL_Surface *surf = pgSurface_AsSurface(self);
    SURF_INIT_CHECK(surf)
    Py_ssize_t bytesize = 0;

    /* Add the size of the python object */
    bytesize += sizeof(pgSurfaceObject);

    /* Add the size of the SDL_Surface struct */

    bytesize += sizeof(SDL_Surface);

    /* Add the size of the SDL_PixelFormat struct and its items */
    if (surf->format) {
        bytesize += sizeof(SDL_PixelFormat);
        if (surf->format->palette) {
            bytesize += sizeof(SDL_Palette);
            if (surf->format->palette->ncolors) {
                bytesize += sizeof(SDL_Color) * surf->format->palette->ncolors;
            }
        }
    }

    /* Add the size of the pixels */
    bytesize += surf->h * surf->pitch;

    return PyLong_FromSsize_t(bytesize);
}
```

**Comment by Starbuck5** [comment]
SDL pixelformat structs and their items can be shared between multiple surfaces.

I agree with Ankith, I don't see this as something that needs to be fixed.

**Comment by zoldalma999** [comment]
I agree, this seems unnecessary. It would be a bit of work, would not be perfectly accurate and I think not a lot of people would use this. [Python docs](https://docs.python.org/3/library/sys.html#sys.getsizeof) also mention that this does not need to be accurate (also, surface is not the only one with the issue, Sound, Mask, PixelArray, Font and possibly more are not accurate either).

I'll close this in a bit (like in a weekish), unless someone objects.
