### ISSUE TITLE
Loading freesansbold through sysfont emits warning

### ISSUE THREAD

**Issue by Starbuck5** [pygame-community/pygame-ce#2319]
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.9.5
- **SDL version** (e.g. SDL 2.0.12): 2.26.5
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.1.3.dev1

**Current behavior:**

Asking for the font "freesansbold" (the default font) causes the font not found warning to be emitted.

**Expected behavior:**

Since you're asking for freesansbold and getting freesansbold, there should not be a warning.

**Test code**

```py
import pygame
pygame.init()
pygame.font.SysFont("freesansbold", 24)
```

**Stack trace/error output/other error logs**

```
C:\Users\charl\AppData\Local\Programs\Python\Python39\lib\site-packages\pygame\sysfont.py:486: UserWarning: The system font 'freesansbold' couldn't be found. Did you mean: 'freesans'? Using the default font instead.
  warnings.warn(
```

**Comment by Starbuck5** [comment]
@Sjmarf this is relevant to your recent sysfont work.

**Comment by Sjmarf** [comment]
The issue seems to be because `freesansbold` isn't actually listed as a valid font, and so Pygame falls back on the default font. Passing `freesansbold` as the font-name has the same effect as passing any arbitrary string of characters.

So in a way, it's behaving exactly as it should do. Would you like me to make a special case for `freesansbold` where it doesn't emit the warning?

**Comment by Starbuck5** [comment]
Freesansbold is the default font!

**Comment by Sjmarf** [comment]
> Freesansbold is the default font!

I'm aware - `"freesansbold"` is just not in the list of valid fonts that it searches for a match against. Because of this, it falls back to the default font, which happens to be called `"freesansbold"`, but Pygame doesn't know that. This is how it has always worked, before I implemented the font warning system.

**Comment by Starbuck5** [comment]
It's not a list of valid fonts, it's a list of system fonts.

Another solution would be to add it to the list of system fonts.

Responding to what I see on discord. `"freesansbold"` is just as valid as `None` as a way to get the system font. They are both hardcoded into the Font constructor.

**Comment by dr0id** [comment]
If my computer does not have "freesansbold" installed, why is it then a SysFont?

And it is not listed in `get_fonts()` nor `match_font(...)`:

```python
>>>"freesansbold" in pygame.font.get_fonts()
False
>>>pygame.font.match_font("freesansbold", True, False)
>>>pygame.font.match_font(None, True, False)
Traceback (most recent call last):
...
  File "...\python311\Lib\site-packages\pygame\sysfont.py", line 534, in match_font
    for single_name in name:
TypeError: 'NoneType' object is not iterable
```

**Comment by MyreMylar** [comment]
> If my computer does not have "freesansbold" installed, why is it then a SysFont?

I mean it does have it because it comes with pygame-ce. I think SysFont is less a collection of fonts that come with the OS when you first install it, and more a collection of fonts that we have found on your system by looking in some known places for fonts - which will include pygame-ce's default font because we know you have that as you are running pygame right now and we know where to look for it.

> And it is not listed in get_fonts() nor match_font(...):

I expect we can add it to those places as well.
