### ISSUE TITLE
ability to call ``pygame.Color.from_colorspace`` methods with more than 4 args + python doctype wrong

### ISSUE THREAD

**Issue by bilhox** [pygame-community/pygame-ce#2386]
**PyGame version**: pygame 2.3.1.dev4

**Current behavior:** We can pass as much arguments as we want to ``pygame.Color.from_colorspace`` methods. Furthermore, python doctype is wrong, for example with ``pygame.Color.from_hsla``, it expects 4 arguments or a tuple of 4 arguments, however we can pass 3 arguments.

**Expected behavior:** Raises an error if too much arguments were passed, and add default value to the last argument (for hsla, hsva, i1i2i3).

**Test code**

```py
import pygame

pygame.init()

screen = pygame.display.set_mode([200,100])

color = pygame.color.Color.from_hsva(130, 40, 12) # technically wrong according to python doctype
color2 = pygame.Color.from_cmy(1., 1., 1., "I like arguments")
color3 = pygame.Color.from_hsla(120, 32, 34, 1, 2234832948, "Mattiss likes fish.")
color4 = pygame.Color.from_i1i2i3([0, 0, 0, 12, 34209, "In a rectangle triangle, a² + b² = c², where 'c' is the hypotenuse length and a and b the length of the two other sides"])

while True:

    screen.fill(color)

    for event in pygame.event.get():
        if event.type == pygame.QUIT or event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
            pygame.quit()
            exit(0)

    pygame.display.flip()
```
This code works perfectly fine.

**Comment by ankith26** [comment]
This is not just limited to the newly added `from_<colorspace>` methods, but the source of the issue is actually in the existing setters for the colorspaces

I think the way we should tackle this is

- Add a deprecation warning on the setters if length of the argument is greater than expected (and in a future version do exact checks)
- Also add a check in the existing color space methods
