### ISSUE TITLE
Documentation misunderstanding in src_py/sprite.py

### ISSUE THREAD

**Issue by TheooKing** [pygame-community/pygame-ce#2403]
In the class `AbstrackGroup` the function `draw` it is said that it return a list of rects, but it always returns back an empty list. It will be nice for the documentation to be updated and include that the return is an empty list.

This case also happens on the other draw functions in class:
- RenderUpdates
- LayeredUpdates

Exception: in the class LayeredDirty

Site Docs:
>draw()
> blit the Sprite images
> draw(Surface) -> List[Rect]
> Draws the contained Sprites to the Surface argument. This uses the Sprite.image attribute for the source surface, and Sprite.rect for the position.
> 
> The Group keeps sprites in the order they were added, they will be drawn in this order.

Code doc for abstract group:
```
       """draw all sprites onto the surface

        Group.draw(surface): return Rect_list

        Draws all of the member sprites onto the given surface.

        """
```

### Questions

Why does it return an empty list? 
And why does it reset the `lostsprites`? And not changing it after?
And what was it supposed to be returning in the first place? Even though it's `dirty` that's being returned i don't see it being changed in the code.

**Comment by Starbuck5** [comment]
I think the piece of the picture you're missing is that the AbstractGroup is inherited by the other group classes. It is an interface that all the group classes follow.

Since LayeredDirty needs to return a list of rects, the draw() method of a Group always needs to return "a list of rects" even if it's empty.

lostsprites seemingly is meaningless in AbstractGroup, but in other group classes the list is actually populated and makes it meaningful for their cases.
