### ISSUE TITLE
give pg.Surface.get_bounding_rect() extra return values

### ISSUE THREAD

**Issue by AndreyVarvar** [pygame-community/pygame-ce#2539]
Context: recently i stumbled upon a problem, that there is no way to determine the position if the bounding rect inside the original image rect.

<img width="200" alt="Screenshot 2023-10-30 at 22 08 45" src="https://github.com/pygame-community/pygame-ce/assets/91492313/b7850e5d-4805-4b81-be1a-12acfc758a59">

red color - image rect,
green color - bounding rect.

Fo example, let's say i store my entity position in the image_rect variable, but then i need to get the bounding rect, with its position being as in relation to image_rect, that means, if the image_rect has a pos of (x, y), the bounding_rect will have a pos of (x+dx, y+dy), where dx, dy are the position of bounding_rect in the image_rect as shown in the example above.

Idea: I thought, that maybe by passing extra-parameters into the `get_bounding_rect()` function, the return values are going to include the position of bounding_rect in the image_rect. This will eliminate the need to store values that can possibly change in the code.

**Comment by bigwhoopgames** [comment]
I believe the Rect it produces is already situated on an offset. You should be able to just get the offset by reading surface.get_bounding_rect().topleft

**Comment by Matiiss** [comment]
Exactly, the rect returned by `get_bounding_rect` is situated relative to the rect you would get with `get_(f)rect`. That means if you want to get a bounding rectangle with world coordinates, you just have to move it by the world coordinates of the position rect.
```py
bounding_rect_in_world = image.get_bounding_rect().move(rect.topleft)  # `rect` is what you get with `get_(f)rect`
```
I will now close this issue as it seems the issue has been resolved because the feature requested already exists.
