### ISSUE TITLE
pygame.Color.from_normalized()

### ISSUE THREAD

**Issue by JiffyRob** [pygame-community/pygame-ce#2645]
**Description**
`pygame.Color` objects can convert to and from RGB, HSLA, HSVA, CMY, and I1I2I3 colorspaces.  They can also convert to an OpenGL style 0-1 RGB space by using the normalize() method, but there is no API to convert back.  Granted it's pretty trivial to multiply and round it yourself, but it's an odd gap in the API that should probably be fixed.

Use case: I'm loading obj and mtl files and they store their colors in the 0-1 color space.  I need the 0-255 space for drawing and rendering purposes.

**Comment by ankith26** [comment]
Agreed, for consistency sake this could be a nice little addition.

Adding a "good first issue" for people looking into contributing to C code, this should not be too complex (and you can look around the existing method implementations in `src_c/color.c` to get a better idea)

**Comment by XFajk** [comment]
> **Description** `pygame.Color` objects can convert to and from RGB, HSLA, HSVA, CMY, and I1I2I3 colorspaces. They can also convert to an OpenGL style 0-1 RGB space by using the normalize() method, but there is no API to convert back. Granted it's pretty trivial to multiply and round it yourself, but it's an odd gap in the API that should probably be fixed.
> 
> Use case: I'm loading obj and mtl files and they store their colors in the 0-1 color space. I need the 0-255 space for drawing and rendering purposes.

so I started looking into this and I have a few questions 

I started with the function that unnormalizes the colors because it seems the easiest but I am not sure how I should implement it since the `normalize()` function returns a tuple so should I just create a method that would create a `pygame.Color` object from that kind of tuple or should it just create a new tuple that has the normal `RGBA` values range from  0 to 255 values what would be more fitting 

and should I even ask you I am kinda new to this contributing stuff when I say new I say this is my first issue so should I be asking the issues creator how am I suppose to implement the feature or should I just implement it and then ask if can be like this if they say no then I remake it

**Comment by Matiiss** [comment]
How about we add a property called `normalized` (internally it might as well call `normalize`, but we also need a setter for it then) and then that easily integrates with the existing C API to add a `from_normalized` classmethod.
This would make the Python API more consistent in that `normalized` is basically a color space that you can get, set and create from.
