### ISSUE TITLE
No acceleration on Linux

### ISSUE THREAD

**Issue by rafaelcp** [pygame-community/pygame-ce#3073]
I'm using Pygame on Ubuntu 22.04 (pygame-ce 2.5, SDL 2.30.6, Python 3.12.4, tried with legacy pygame before and same thing) and noticed that it was way slower than Pyglet. After a bit of search, I found about pygame.display.Info(), and here is its output:

```
<VideoInfo(hw = 0, wm = 1,video_mem = 0
blit_hw = 0, blit_hw_CC = 0, blit_hw_A = 0,
blit_sw = 0, blit_sw_CC = 0, blit_sw_A = 0,
bitsize = 32, bytesize = 4,
masks = (0x00ff0000, 0x0000ff00, 0x000000ff, 0x00000000),
shifts = (16, 8, 0, 0),
losses = (0, 0, 0, 8),
current_w = 640, current_h = 480
pixel_format = PIXELFORMAT_RGB888)
```
It seems it can't detect anything, it can't even do software acceleration. I have an RTX 3090 installed and being used normally by other applications. Any hints about what's happening and how to fix it?

**Comment by Starbuck5** [comment]
I believe pyglet uses OpenGL.

Pygame-ce does not use OpenGL, which is why it is more portable than pyglet (it runs on raspberry pi). Our backend is SDL, and we use SDL_Surface based rendering, which is on the CPU. SDL has a gpu backend with SDL_Renderer and we are experimenting with bringing that API into pygame-ce, but it would be a separate API, outside of pygame.Surface.

Looking through our source code I don't see a path where video_mem would ever be populated.

**Comment by ankith26** [comment]
I think this issue can be closed now that the question has been addressed. It isn't technically feasible to add hardware acceleration to the current API so as starbuck said, it will be implemented separately.
