### ISSUE TITLE
integer cast function for the math.VectorX

### ISSUE THREAD

**Issue by XFajk** [pygame-community/pygame-ce#3109]
I was thinking if making a method that turns floats in the Vector to integers would be a good addition because in my last project I found my self doing `pygame.Vector2(int(other_vector.x), int(other_vector.y))` and something like `other_vector.copy().int()` would maybe be more readable 

also I can and would want to implement this I am just making an issue to get it approved that I can add this and also I to link the pull request to this issue

**Comment by damusss** [comment]
It is technically not the same thing, but have considered using the round() function instead?  It returns a vector with each component rounded. (1.2 -> 1, 2.6 -> 3)

**Comment by damusss** [comment]
@XFajk the round() functionality is implement trough `__round__` magic method (95% confident) so the best course of action could be to implement the `__int__` method, but there might be reasons it wasn't done before that I'm not aware of.
```py
class Custom:
    def __init__(self, any: float):
        self.any = any

    def __int__(self):
        print("int called")
        return int(self.any)

print(int(Custom(2.8)))
```
(example, for Vector2 it would be needed to be done in C)

**Comment by XFajk** [comment]
@damusss I could just try to implement the int method if some unrelated tests fail I will just close the issue

**Comment by aatle** [comment]
Hey @XFajk, note that you would not use the `__int__` method to implement this behavior because `__int__` must return an integer.
Better options would be `__trunc__`, `__floor__`, and `__ceil__`. However, that the `math` module docs for these all say that [the method should return a valid `number.Integral` value](https://docs.python.org/3/library/math.html#math.floor).

Personally, I don't think any new implementation is needed, because there are ways to get similar behavior:
- All pygame functions that take pixel coordinates automatically truncate the decimal
- You can *floor* (note that your examples *truncates*) a vector with floor division by 1: `pygame.Vector2(1.3, -1.6) // 1`, giving a new vector
- You can *round* a vector with `round()`, giving a new vector
- I think the provided use case is uncommon. Feel free to elaborate more on your use case.

**Comment by XFajk** [comment]
@damusss I see one tiny issue the __int__ method return a int so it can't implemented through __int__ method so should I just implement it differently or do something else?

**Comment by XFajk** [comment]
@aatle yeah you right I tried to implement it but I ran into the __int__ can only return a integer problem and I dont see a better way to implement this that would feel weird
