### ISSUE TITLE
camera on OLPC greyscale issue (1417)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#804]
#  **Issue &numero;1417 opened by *[illume](https://github.com/illume)* at 2019-10-14 13:13:36**

src_c/_camera.c `sbggr8_to_rgb()`

This was written:
> Seems to be grayscale and kind of dark on the OLPC XO Maybe the result of a different Bayer color order on the screen? */

It's a very old comment... so maybe it's not true (then, or any more).

**Related Docs:** https://www.pygame.org/docs/ref/camera.html<hr>

#  Comments

# # #  **[MyreMylar](https://github.com/MyreMylar)* commented at 2020-05-15 20:16:49*

The OLPC XO is one of these by the way:

https://en.wikipedia.org/wiki/OLPC_XO

I have no idea how to test this.

**Comment by MyreMylar** [comment]
I'm closing this. 

OLPC seems to be pretty dead as a hardware platform (last release in 2012) and this comment is presumably (based on the name) related to to an even earlier version released in 2006. Raspberry pi seems to cover this low cost market better and is much more widely (& recently) supported. So much so that one of the 'recent' blog posts on the OLPC website talks about [using their OS on Raspberry Pi](http://blog.laptop.org/2020/03/06/olpc-os-on-raspberry-pi/).
